# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

ARG BASE_VERSION=15
FROM ghcr.io/daemonless/base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG PACKAGES="redis"

# --- Metadata (Injected by Generator) ---
LABEL org.opencontainers.image.title="Redis" \
      org.opencontainers.image.description="Redis key-value store on FreeBSD." \
      org.opencontainers.image.source="https://github.com/daemonless/redis" \
      org.opencontainers.image.url="https://redis.io/" \
      org.opencontainers.image.licenses="BSD-2-Clause" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Databases" \
      io.daemonless.port="6379" \
      io.daemonless.volumes="/config" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.pkg-source="containerfile" \
      io.daemonless.packages="${PACKAGES}"

# Install Redis
RUN pkg update && \
    pkg install -y ${PACKAGES} && \
    mkdir -p /app && pkg info redis | sed -n 's/.*Version.*: *//p' > /app/version && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Create directories
RUN mkdir -p /config/data /run/redis && \
    chown -R bsd:bsd /config /run/redis

# Copy service files
COPY root/ /
RUN chmod +x /etc/services.d/*/run /etc/cont-init.d/* 2>/dev/null || true

ENV REDIS_DATA=/config/data

# --- Expose (Injected by Generator) ---
EXPOSE 6379

# --- Volumes (Injected by Generator) ---
VOLUME /config